kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: rust
    commands:
      - cargo build
      - cargo test
    publish:
      image: plugins/docker
      settings:
        username: admin
        password: $REGISTRY_PASS
        repo: http://harbor.norspang.dk/beerated-backend
