kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: rust
    commands:
      - cargo build
      - cargo test
  - name: publish
    image: plugins/docker
    settings:
      username: admin
      password: 
        from_secret: REGISTRY_PASS
      registry: http://harbor.norspang.dk
      repo: http://harbor.norspang.dk/beerated-backend
      insecure: true
