kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: rust
    commands:
      - cargo build
      - cargo test
  - name: publish
    image: plugins/docker
    settings:
      username: Norspang
      password: 
        from_secret: REGISTRY_PASS
      registry: norspang/beerated-backend
