kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: rust
    commands:
    - cargo build
    - cargo test
  - name: publish
    image: plugins/docker
    environment:
      PASSWORD:
        from_secret: REGISTRY_PASS
    settings:
      username: norspang
      password: $PASSWORD
    repo: norspang/beerated-backend
