FROM rust:1.62 as build
COPY . .
RUN cargo build --release


FROM debian:buster-slim
COPY --from=build ./target/release/beerated-backend ./target/release/beerated-backend
EXPOSE 8000
ENV ROCKET_ADDRESS=0.0.0.0

CMD ["/target/release/beerated-backend"]
